version: '3.8'

services:
  incident-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: incident-management-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - incident-network

networks:
  incident-network:
    driver: bridge
